import './globals.css'
import { Inter } from 'next/font/google'
import { SessionProvider } from "next-auth/react"

// function App({Component, pageProps}){
//   return(
//     <SessionProvider session={pageProps.session}>
//       <Component {...pageProps}/>
//     </SessionProvider>
//   )
// }
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Home Page',
  description: 'Generated by create next app',
}

// export default App

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
